#!/bin/bash

# Get the current time
NOW=$(date +%Y-%m-%d-%M-%S)
	
echo "What Network Interface would you like to use?
1. wlan1
2. wlan0
3. exit"
read NET
case $NET in 
	2) echo "Using wlan0";

	#Activating Monitor Mode
	echo "Activating Monitor Mode";
	sudo airmon-ng;
	sudo airmon-ng check kill;
	sudo airmon-ng wlan0;
	sudo iwconfig;

	# Start airodump-ng and save the output to a file
	sudo airodump-ng wlan0 -w $NOW-output --output-format csv;
	awk 'NR ==3, NR ==28 {print" MAC: " $1, " NAME: "$19,$20,$21}' $NOW-output-01.csv > $NOW-OUT;
	sed 's/,/ /g' $NOW-OUT > OutputFiles/$NOW-SCAN.txt;
	

	# Wait for airodump-ng to finish
	sleep 15;

	# kill airodump-ng
	killall airodump-ng;

	#remove other files
	rm $NOW-output-01.csv;
	rm $NOW-OUT;;

	
	1) echo "Using wlan1";

	#Activating Monitor Mode
	echo "Activating Monitor Mode";
	sudo airmon-ng;
	sudo airmon-ng check kill;
	sudo airmon-ng wlan1;
	sudo iwconfig;

	# Start airodump-ng and save the output to a file
	sudo airodump-ng wlan1 -w $NOW-output --output-format csv;
	awk 'NR ==3, NR ==28 {print" MAC: " $1, " NAME: "$19,$20,$21}' $NOW-output-01.csv > $NOW-OUT;
	sed 's/,/ /g' $NOW-OUT > OutputFiles/$NOW-SCAN.txt;

	# Wait for airodump-ng to finish
	sleep 15;

	# kill airodump-ng
	killall airodump-ng;

	#remove other files
	rm $NOW-output-01.csv;
	rm $NOW-OUT;;

	3) exit;;
esac



